services:
  db:
    container_name: docker-postgres
    image: postgres:16
    ports:
      - 5433:5432
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  python:
    container_name: python
    build:
      context: .
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  trino:
    container_name: trino
    ports:
      - "8080:8080"
    image: "trinodb/trino:444"
    volumes:
      - ./docker/trino/etc:/usr/lib/trino/etc:ro
      - ./docker/trino/catalog:/etc/trino/catalog
    environment:
      - CATALOG_MANAGEMENT=dynamic
    networks:
      - backend

  spark-master:
    container_name: spark-master
    build: ./docker/spark
    ports:
      - "9090:8080"
      - "7077:7077"
      - "10000:10000"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - backend
  spark-worker-a:
    build: ./docker/spark
    container_name: spark-worker-a
    env_file:
      - .env
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    networks:
      - backend
  spark-worker-b:
    build: ./docker/spark
    container_name: spark-worker-b
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
    networks:
      - backend

  jupyterlab:
    container_name: jupyterlab
    build: ./docker/jupyter
    environment:
      - JUPYTER_PORT=8089
    volumes:
      - ./notebooks:$LAB_HOME
      - ./data:$LAB_HOME/data
    env_file:
      - .env
    ports:
      - "8089:8089"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
