[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra"
testpaths = ["tests"]
pythonpath = "air/dags"

[tool.bandit]
exclude_dirs = ["tests"]

[tool.coverage.report]
skip_covered=true
show_missing=true
