name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      LAB_HOME: /home/jovyan

      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 5G
      SPARK_DRIVER_MEMORY: 5G
      SPARK_EXECUTOR_MEMORY: 5G


    steps:
      - uses: actions/checkout@v3
      - name: Build the docker-compose stack
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps -a
